### ISSUE TITLE
Can you add some badges on your readme?

### ISSUE THREAD

**Issue by TofPlay** [jinmingjian/sde#16]
Very interesting tool 👍 😍

Can you add some badges like these:
![Ubuntu](https://img.shields.io/badge/Ubuntu-16.04-6193DF.svg) ![Visual Studio Code Version](https://img.shields.io/badge/Visual%20Studio%20Code-1.8.1-6193DF.svg) ![SDE Version](https://img.shields.io/badge/SDE-1.0.20170114-6193DF.svg) ![Swift Version](https://img.shields.io/badge/Swift-3.0.2-orange.svg) [![SwiftPM compatible](https://img.shields.io/badge/SwiftPM-compatible-brightgreen.svg)](https://github.com/apple/swift-package-manager) ![Plaforms](https://img.shields.io/badge/Platform-Linux|macOS-lightgrey.svg) ![License MIT](https://img.shields.io/badge/License-Apache%20v2-lightgrey.svg)

**Comment by jinmingjian** [comment]
@TofPlay thanks! Yes, cool badges, I like all of them! :heart:

**Comment by jinmingjian** [comment]
fixed
