### ISSUE TITLE
Warning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by vknabel** [jinmingjian/sde#18]
I am not 100% sure wether sde emitted this warning in VS Code and what it means in that context. The only other Swift related extension was SwiftLint.

After I finished the standby mode of my Mac I saw the following log entry.

```
(node:91267) Warning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
```

<img width="440" alt="bildschirmfoto 2017-01-18 um 10 52 55" src="https://cloud.githubusercontent.com/assets/2100336/22059251/5633c6d2-dd6c-11e6-9aca-7c73a790e840.png">

**Comment by jinmingjian** [comment]
yes, I also have noticed this message:) I have scanned the concerned leaking suspects. From eyes, they are good. I may use some node profiler to help this. Thanks:)

**Comment by jinmingjian** [comment]
solve by #9
