### ISSUE TITLE
more controllable interface to sourcekit

### ISSUE THREAD

**Issue by jinmingjian** [jinmingjian/sde#9]
1.  a quick swift version of sourcekitf-repl

2.  implement a new LSP(Language Server Protocol) natively
It is an interesting direction and would be much helpful if doing it in a right way. However, I thnk it makes less attractive to just replace node version LSP with swift version.
REF: https://github.com/Microsoft/language-server-protocol

**Comment by jinmingjian** [comment]
we may link to two different libraries in linux/osx ...

**Comment by jinmingjian** [comment]
choose 1:
1. no change to current implementation
2. text based comm is easier to debug and still much fast enough for UI. (In fact, the performance of pipe itself is higher than socket.)
3. best, we can eat own dog food!

**Comment by jinmingjian** [comment]
note: unlike the Sourcekitten and RL's LSP. we only add a mini thin wrapper to sourcekit

**Comment by Dan2552** [comment]
Hey, I started a [very similar project to this for Sublime Text](https://github.com/Dan2552/SourceKittenSubl) (currently using SourceKitten), so I'm very curious what you intend to do here. I don't really understand what you're planning from what you've already written. Please could you elaborate a bit?

**Comment by jinmingjian** [comment]
@Dan2552  SourceKitten is great. The problem is that it is **uncontrollable** for me.

As my testing, it just can be compiled but **not work for non-trivial cases for Linux** in the end of Dec, 2016.

And add following reason:
1. I have not seen two much additions from SourceKitten for many cases at least. 
2. There is overlapped areas between SourceKitten and effort in editor/IDE like project. A simple example, we need map sourcekit 's syntax kind to editor's kind. SourceKitten also do a mapping for you firstly. These works done in SourceKitten are redundant. From engineering, this is bad in many aspects.
3. above 2 and "uncontrollable" leave hidden troubles for future. i.e., we may want refactoring...
4. I want to start server side Swift @ Linux as soon as possible. I do not want to wait for SourceKitten.

Further, I am more interesting to the [RL's project](https://github.com/RLovelett/langserver-swift), which is related to this [Swift bug](https://bugs.swift.org/browse/SR-1878). But I am afraid that RL are **not** doing much right from current sources.

The true benefit of LS is that it becomes a standard and may be shared by other ide projects, like you subl(if you have client to support...). This does not mean it is higher performance or easier to use.

**Comment by jinmingjian** [comment]
have an one-day open mind :smile: 

in fact, the SDE now has provided a LS in this arch:

client -------| node LS front-end | --- F2B brige ---- | swift LS backend | ----------- sourcekit

F2B bridge came with this new LS backend will change to new neat engine to solve #18 BTW.

**Comment by jinmingjian** [comment]
The new LS backend(sourcekite) is written in Swift. Given the ABI Stability of Swift and my experience, the native LS backend will not shipped in the SDE extension package. It is recommended to build the sourcekite by users. It should be a piece of cake. And the "swift.sourcekit.use_built_in_bin" option has gone in 2.0.

**Comment by jinmingjian** [comment]
done in 43d8f8a581cb626139116e3006bf7052573ff108
